version: "3.4"

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "ms-stock-db"
    ports:
      - "3306:3306"