version: "3.4"

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  postgres:
    container_name: postgres
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres